# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VwBAazrf_oesb1jY_l2ODo5KajJGUSFA
"""

import random
import string

def generate_password(length, include_digits=True, include_symbols=True):
  

  letters = string.ascii_letters
  digits = string.digits if include_digits else ''
  symbols = string.punctuation if include_symbols else ''


  chars = letters + digits + symbols
  password = ''.join(random.choice(chars) for _ in range(length))
  #password consisting of both strings and digits 

  return password


  password = generate_password(20)
  print(password)

password = generate_password(10)
print(password)

